[package]
name = "aggregate"
version = "0.1.0"
edition = "2021"

[dependencies]
secp256kfun = "0.10"
# k256 = "0.13.3"
rand = "0.8.5"
schnorr_fun = "0.10.0"
sha2 = "0.10.8"
# secp256k1 = { version = "0.29.1", features = ["rand", "hashes"]}
